package/python-pudb: bump to version 2024.1
This bump will fix the following build failure raised since commit
8937db8dd595e0988751e5dbb568e870b07b39cc thanks to
https://github.com/inducer/pudb/commit/8c8f9d4a25e226e77a18d4d938eecf2f969e9b32:

FileExistsError: File already exists: /home/buildroot/instance-0/output-1/target/usr/lib/python3.11/site-packages/test/__init__.py

https://github.com/inducer/pudb/compare/v2023.1...v2024.1

Fixes: 8937db8dd595e0988751e5dbb568e870b07b39cc
 - http://autobuild.buildroot.org/results/0e3b15b9d02dda231f768595cdcff4e75ad71afd

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>