package/nginx: select libxcrypt with glibc
Fix the following build failure raised since bump of glibc to version
2.39 in commit b5680f53d60acf8ff6010082f873438a39bd5d97:

In file included from src/core/ngx_config.h:26,
                 from src/core/nginx.c:8:
src/os/unix/ngx_linux_config.h:55:10: fatal error: crypt.h: No such file or directory
   55 | #include <crypt.h>
      |          ^~~~~~~~~

Fixes: b5680f53d60acf8ff6010082f873438a39bd5d97
 - http://autobuild.buildroot.org/results/a186fffc468f9c901626c47c4ce216ae501085b8

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>