package/flashrom: disable -Werror
Disable -Werror to avoid the following build failure raised since bump
to version 1.3.0 in commit 073b0fc9c1fe9945eccf4b792b948633aae9a9b8:

chipset_enable.c:27: error: "_LARGEFILE64_SOURCE" redefined [-Werror]
   27 | #define _LARGEFILE64_SOURCE
      |
<command-line>: note: this is the location of the previous definition

Fixes:
 - http://autobuild.buildroot.org/results/b8d8c30d1306c2ba8f59b48f457a7ef930306b8c

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>