package/tiff: explicitly disable lerc support for host and target
We do not have liblerc in Buildroot and it may cause linking issues for
host-tiff on build hosts with liblerc:

libtool: link: /usr/bin/gcc -O2
-I/home/dragon/src/ft/ftcommunity-TXT/output/build/rootfs/per-package/host-tiff/host/include
-Wall -W -Wl,-rpath
-Wl,/home/dragon/src/ft/ftcommunity-TXT/output/build/rootfs/per-package/host-tiff/host/lib
-o tiffcp tiffcp.o
-L/home/dragon/src/ft/ftcommunity-TXT/output/build/rootfs/per-package/host-tiff/host/lib
../libtiff/.libs/libtiff.so ../port/.libs/libport.a -lLerc -ljbig -lm
-Wl,-rpath
-Wl,/home/dragon/src/ft/ftcommunity-TXT/output/build/rootfs/build/host-tiff-4.6.0/libtiff/.libs
-Wl,-rpath
-Wl,/home/dragon/src/ft/ftcommunity-TXT/output/build/rootfs/per-package/host-tiff/host/lib
/usr/bin/ld: ../libtiff/.libs/libtiff.so: undefined reference to
`deflateInit_'
/usr/bin/ld: ../libtiff/.libs/libtiff.so: undefined reference to `deflate'
/usr/bin/ld: ../libtiff/.libs/libtiff.so: undefined reference to
`deflateEnd'
/usr/bin/ld: ../libtiff/.libs/libtiff.so: undefined reference to `inflate'

Signed-off-by: Peter Korsgaard <peter@korsgaard.com>