package/python-pygame: drop package
The python-pygame package has not recieved any update since
Sun May 1 22:15:17 2016 (commit: a9ec96e545102ae5ccd4280323d35360b0a5072d)

Also, this package no longer builds properly against python 3.12.0. Receiving
the following error when building:

```
src/surface.c:2812:14: error: invalid type argument of unary ‘*’ (have
‘int’)
 2812 |         ch = *PyUnicode_AS_UNICODE (obj);
      |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~
src/surface.c: In function ‘PySurface_Blit’:
```

If someone wants to re-introduce this package at a later date they are more
than welcome to do so!

Signed-off-by: Adam Duskett <adam.duskett@amarulasolutions.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>