package/igt-gpu-tools: disable tests
Disable tests to avoid the following build failure raised since the
addition of the package in commit
d8a729d1731339da141612be33c5e59bc9928748:

../tests/intel/kms_pm_backlight.c: In function '__igt_unique____real_main257':
../tests/intel/kms_pm_backlight.c:320:32: error: implicit declaration of function 'basename'; did you mean 'rename'? [-Werror=implicit-function-declaration]
  320 |                         name = basename(full_name);
      |                                ^~~~~~~~
      |                                rename

Fixes: d8a729d1731339da141612be33c5e59bc9928748
 - http://autobuild.buildroot.org/results/ff5de58ca9408f3a4fc6b6d5bd8c62093c1021ad

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>