package/newlib-bare-metal: fix legal-info
Hash of COPYING.NEWLIB is wrong since the addition of the package in
commit 3b95ff658bf4859eb5cffd28cbbedd1826fad9a6:

ERROR: COPYING.NEWLIB has wrong sha256 hash:
ERROR: expected: 422aa40293093fb54fc66e692a0d68fd0b24ed5602e5d1d33ad05ba3909057e9
ERROR: got     : 9a59b4ee3af067045fe0ea78786201c42d54756fe48cbccf44f3dfc398474717

Fixes: 3b95ff658bf4859eb5cffd28cbbedd1826fad9a6
 - No autobuilder failures (yet)

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>