package/janet: needs MMU
janet unconditionally uses fork since version 1.32.0 and
https://github.com/janet-lang/janet/commit/4b8c1ac2d2d5c13d7c8592fd6d94b34a6a8b3549
resulting in the following build failure since bump to version 1.32.1 in
commit c87abf01a9153a2b2fe6c046fa83c86db92d79a7:

janet.c:(.text+0x19bbc): undefined reference to `fork'

Fixes:
 - http://autobuild.buildroot.org/results/f0771fc6c9905d3a6d60ce245df585b3c6096f7f

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>