package/rauc-hawkbit-updater: fix build with gcc 4.8
Fix the following build failure with gcc 4.8 raised since the addition
of the package in commit 928b7219cd7079864eadadc66dbff21c5cd72804:

../src/hawkbit-client.c:873:17: error: 'for' loop initial declarations are only allowed in C99 mode
                 for (const gint *code = &resumable_codes[0]; *code; code++)
                 ^
../src/hawkbit-client.c:873:17: note: use option -std=c99 or -std=gnu99 to compile your code

Fixes: 928b7219cd7079864eadadc66dbff21c5cd72804
 - http://autobuild.buildroot.org/results/e275d0ec4fe1da418a6163b46666316034b83b19

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>