package/libusb-compat: fix hash
Upstream re-released the v0.1.8 tarballs with autotools related stuff. [1]
That makes the hash test to fail:

ERROR: while checking hashes from package/libusb-compat//libusb-compat.hash
ERROR: libusb-compat-0.1.8.tar.bz2 has wrong sha256 hash:
ERROR: expected: 698c76484f3dec1e0175067cbd1556c3021e94e7f2313ae3ea6a66d900e00827
ERROR: got     : b692dcf674c070c8c0bee3c8230ce4ee5903f926d77dc8b968a4dd1b70f9b05c
ERROR: Incomplete download, or man-in-the-middle (MITM) attack

Update the hash and drop LIBUSB_COMPAT_AUTORECONF.

[1] https://github.com/libusb/libusb-compat-0.1/issues/28#issuecomment-1759400548

[Peter: use .tar.gz to not conflict with s.b.o]
Signed-off-by: Sébastien Szymanski <sebastien.szymanski@armadeus.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>