package/libgeos: needs gcc >= 4.9
libgeos needs gcc >= 4.9 since bump to version 3.12.0 in commit
16727d4595dd1972a46e92bbd2260a896cc19b60 and
https://github.com/libgeos/geos/commit/289ed4efb26a9944f4385381e1574184b1e7448e:

In file included from /home/thomas/autobuild/instance-0/output-1/build/libgeos-3.12.0/src/algorithm/ConvexHull.cpp:30:0:
/home/thomas/autobuild/instance-0/output-1/build/libgeos-3.12.0/include/geos/util.h:38:12: error: 'std::make_unique' has not been declared
 using std::make_unique;
            ^

This dependency is propagated to libgeos only reverse dependency,
postgis.

Fixes:
 - http://autobuild.buildroot.org/results/56bb572fb1d56d45dbb950a73b9b888239fa6968

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Reviewed-by: Maxim Kochetkov <fido_max@inbox.ru>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>