configs/avenger96_defconfig: fix CI build error due to a missing package for uboot
This refers to https://gitlab.com/buildroot.org/buildroot/-/jobs/6813124907
The build error referenced in that link is:

error: command 'swig' failed: No such file or directory
make[4]: *** [scripts/dtc/pylibfdt/Makefile:33: rebuild] Error 1
make[3]: *** [scripts/Makefile.build:397: scripts/dtc/pylibfdt] Error 2
make[2]: *** [Makefile:2014: scripts_dtc] Error 2
make[1]: *** [package/pkg-generic.mk:283: /builds/buildroot.org/buildroot/output/build/uboot-2024.01/.stamp_built] Error 2
make: *** [Makefile:82: _all] Error 2

BR2_TARGET_UBOOT_NEEDS_PYLIBFDT is added to the avenger96_defconfig in order to resolve the issue

Signed-off-by: Marleen Vos <marleen.vos@mind.be>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>