package/conmon: fix build with gcc 4.8
Fix the following build failure with gcc 4.8 raised since the addition
of the package in commit 06f50ff1bf066feb6cf6ed512113773f87c884fb:

src/conmon.c:5:2: error: #error conmon.c requires C99 or later
 #error conmon.c requires C99 or later
  ^

Fixes: 06f50ff1bf066feb6cf6ed512113773f87c884fb
 - http://autobuild.buildroot.org/results/b573aceefde04435ea13dfd2a48f9c2372bde4d7

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>