configs/qemu_sparc_ss10_defconfig: fix linux hash
Commit c3e17c407a3 (configs/qemu_sparc_ss10: re-introduce defconfig) added a
hash file for the Linux kernel, but mistakingly used the .tar.gz instead of
.tar.xz.

The patch fixes "make legal-info" for qemu_sparc_ss10 configuration:

>>> host-gcc-initial 13.2.0 Collecting legal info
COPYING: OK (sha256: 231f7edcc7352d7734a96eef0b8030f77982678c516876fcb81e25b32d68564c)
COPYING3: OK (sha256: 8ceb4b9ee5adedde47b31e975c1d90c73ad27b6b165a1dcd80c7c545eb65b903)
COPYING.LIB: OK (sha256: a9bdde5616ecdd1e980b44f360600ee8783b1f99b8cc83a2beb163a0a390e861)
COPYING3.LIB: OK (sha256: a853c2ffec17057872340eee242ae4d96cbf2b520ae27d903e1b2fef1a5f9d1c)
ERROR: No hash found for linux-6.8.6.tar.xz

Signed-off-by: Dario Binacchi <dario.binacchi@amarulasolutions.com>
[Peter: extend commit message]
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>