package/dav1d: fix riscv32 build
Fix the following riscv32 build failure raised since bump to version
1.4.1 in commit d8c440936d51b7f76472b43002780f5490b7a3bf and
https://github.com/videolan/dav1d/commit/43ee02a99cce1f221bdb574c9ee484180d71013f:

/home/buildroot/autobuild/run/instance-0/output-1/host/opt/ext-toolchain/bin/../lib/gcc/riscv32-buildroot-linux-gnu/13.2.0/../../../../riscv32-buildroot-linux-gnu/bin/ld: src/libdav1d_bitdepth_8.a.p/itx_tmpl.c.o: in function `.L0 ':
itx_tmpl.c:(.text.unlikely+0x76c): undefined reference to `dav1d_inv_txfm_add_dct_dct_4x4_8bpc_rvv'

Fixes: d8c440936d51b7f76472b43002780f5490b7a3bf
 - http://autobuild.buildroot.org/results/28192c494c7a2f88cc90205b6a08afd11782df40

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>