package/perl-net-ssleay: bump to version 1.94
This bump will fix the following build failure with libressl raised
since commit 9d8f9c73a2fd087dd2e8d8853a80da605fa64e4b:

SSLeay.c: In function 'XS_Net__SSLeay_X509_policy_tree_free':
SSLeay.c:17730:9: error: unknown type name 'X509_POLICY_TREE'
17730 |         X509_POLICY_TREE *      tree = INT2PTR(X509_POLICY_TREE *,SvIV(ST(0)))
      |         ^~~~~~~~~~~~~~~~

https://metacpan.org/dist/Net-SSLeay/changes

Fixes: 9d8f9c73a2fd087dd2e8d8853a80da605fa64e4b
 - http://autobuild.buildroot.org/results/974b7cdd275249c888fc6205f6ca31a3cf28b18f

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle <arnout@mind.be>