package/tllist: fix build with gcc 4.8
Fix the following build failure with gcc 4.8 raised since the addition
of the package in commit 996b786cfc03c3cf2ac631045650545c901e3075:

In file included from ../test.c:7:0:
../test.c: In function 'main':
../tllist.h:213:17: error: 'for' loop initial declarations are only allowed in C99 mode
                 for (int _i = 0; _i < __insize; _i++) {                 \
                 ^

Fixes: 996b786cfc03c3cf2ac631045650545c901e3075
 - http://autobuild.buildroot.org/results/e82fdf4f9ef199e1baa169d38a75872bddd4e6dd

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>