package/sdbus-cpp: fix host build
cmake options were renamed by
https://github.com/Kistler-Group/sdbus-cpp/commit/0074c79e7fd7983dda3c2a4e4ac7febe67751a28
resulting in the following host build failure since bump to version
2.0.0 in commit 0f5bb364c629dd7fc91f4295f872e46d89c0feef:

/home/buildroot/autobuild/run/instance-1/output-1/build/host-sdbus-cpp-2.0.0/src/Proxy.cpp: In member function 'virtual sdbus::PendingAsyncCall sdbus::internal::Proxy::callMethodAsync(const sdbus::MethodCall&, sdbus::async_reply_handler, uint64_t)':
/home/buildroot/autobuild/run/instance-1/output-1/build/host-sdbus-cpp-2.0.0/src/Proxy.cpp:125:91: sorry, unimplemented: non-trivial designated initializers not supported
                                                                       , .floating = false });
                                                                                           ^
/home/buildroot/autobuild/run/instance-1/output-1/build/host-sdbus-cpp-2.0.0/src/Proxy.cpp:133:60: error: class template argument deduction failed:
     auto asyncCallInfoWeakPtr = std::weak_ptr{asyncCallInfo};
                                                            ^

Fixes: 0f5bb364c629dd7fc91f4295f872e46d89c0feef
 - http://autobuild.buildroot.org/results/66668261d05203575658a243e02e78cf77018d8c

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>