package/tesseract-ocr: bump to version 5.3.3
Drop patches (already in version)

This bump will fix the following build failure raised since bump of
leptonica to version 1.83.1 in commit
a4e713558dfd9a6fd6c0677b4b094adc216b720e thanks to
https://github.com/tesseract-ocr/tesseract/commit/27b1827ccde6014df1231e1cec6263ee108066e9:

src/textord/devanagari_processing.cpp: In member function 'bool tesseract::ShiroRekhaSplitter::Split(bool, tesseract::DebugPixa*)':
src/textord/devanagari_processing.cpp:130:19: error: invalid use of incomplete type 'struct Pixa'
  130 |     Box *box = ccs->boxa->box[i];
      |                   ^~
In file included from /home/autobuild/autobuild/instance-5/output-1/host/bin/../s390x-buildroot-linux-gnu/sysroot/usr/include/leptonica/alltypes.h:52,
                 from /home/autobuild/autobuild/instance-5/output-1/host/bin/../s390x-buildroot-linux-gnu/sysroot/usr/include/leptonica/allheaders.h:35,
                 from src/textord/devanagari_processing.h:16,
                 from src/textord/devanagari_processing.cpp:25:
/home/autobuild/autobuild/instance-5/output-1/host/bin/../s390x-buildroot-linux-gnu/sysroot/usr/include/leptonica/bmf.h:48:12: note: forward declaration of 'struct Pixa'
   48 |     struct Pixa  *pixa;        /*!< pixa of bitmaps for 93 characters        */
      |            ^~~~

https://github.com/tesseract-ocr/tesseract/blob/5.3.3/ChangeLog

Fixes:
 - http://autobuild.buildroot.org/results/46d3ffc8885245ee9a56a528be055b0b27a18245

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>