package/prboom: fix build with autoconf >= 2.72
Set ac_cv_type_gid_t=yes to avoid the following build failure raised
since bump of autoconf to version 2.72 in commit
524f3536029dace3ce9aa154d3ca4685582e1955:

In file included from i_network.c:37:
../../config.h:207:15: error: two or more data types in declaration specifiers
  207 | #define gid_t int
      |               ^~~

Fixes: 524f3536029dace3ce9aa154d3ca4685582e1955
 - http://autobuild.buildroot.org/results/0d74517129130e6f26dc8c8aacae175ed8bd4b54

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>