package/spirv-tools: needs gcc >= 8
spirv-tools unconditionally includes filesystem since its addition in
commit 0a01085abeb7d8a097cb68b9f7f4faec7711543c resulting in the
following build failure:

/home/buildroot/autobuild/run/instance-1/output-1/build/spirv-tools-1.3.261.1/tools/objdump/objdump.cpp:15:10: fatal error: filesystem: No such file or directory
 #include <filesystem>
          ^~~~~~~~~~~~

Fixes: 0a01085abeb7d8a097cb68b9f7f4faec7711543c
 - http://autobuild.buildroot.org/results/aaeb0ca8773842768f9311fc804bb7529d9e3bfa

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>