package/libxml2: bump to version 2.12.3
This bump will fix the following build failure with libmodsecurity (and
a lot of other packages) raised since bump of libxml2 to version 2.12.1
in commit d8ac52108c12f0fcc9641b63e7922009270f96c6:

modsecurity.cc: In constructor 'modsecurity::ModSecurity::ModSecurity()':
modsecurity.cc:89:5: error: 'xmlInitParser' was not declared in this scope
   89 |     xmlInitParser();
      |     ^~~~~~~~~~~~~

https://gitlab.gnome.org/GNOME/libxml2/-/blob/v2.12.3/NEWS

Fixes:
 - http://autobuild.buildroot.org/results/d6749bacf6c7c04a74e136585d36bc731716f6fd

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>