package/libcgroup: needs threads
threads are mandatory since the addition of the package in commit and
https://github.com/libcgroup/libcgroup/commit/99ccdf671e9df5b13f646e1487393d562aa7fa62
resulting in the following build failure since commit
9d58b525fcfd0d92fcdd3c66d7858213c4b139c6 which enables build on uclibc
and musl:

In file included from config.c:30:
./libcgroup-internal.h:29:10: fatal error: pthread.h: No such file or directory
   29 | #include <pthread.h>
      |          ^~~~~~~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/87c4454aee97b6955f461651c41c4186a8838c4d

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>