configs/beaglebone_qt5_defconfig: fix Linux compilation errors
Bumping to TI's most recent Linux 4.19 version (i.e. linux-4.19.94-ti-r72)
does not fix compilation errors but allows you to cleanly apply the
necessary patches.

Two errors have been fixed:

 1 Since commit e88225ed88208 ("package/binutils: make 2.41 the default
   version"), the Linux kernel is failing to build with this output:

   arch/arm/mm/proc-v6.S:267: Error: junk at end of line, first unrecognized character is `#'
   make[3]: *** [scripts/Makefile.build:403: arch/arm/mm/proc-v6.o] Error 1

   The patch [1] fixes the issue.

 2 Since commit dc0f7215c604e ("package/gcc: switch to 13.x as default"),
   the Linux kernel is failing to build with this output:

   In file included from ./include/linux/kernel.h:10,
                    from drivers/ata/libahci.c:35:
   drivers/ata/libahci.c: In function ‘ahci_led_store’:
   ./include/linux/compiler.h:348:45: error: call to ‘__compiletime_assert_1154’ declared with attribute error: BUILD_BUG_ON failed: sizeof(_s) > sizeof(long)
     348 |         _compiletime_assert(condition, msg, __compiletime_assert_, __LINE__)

   The patch [2] allows to cleanly apply patch [3] that fixes the issue.

[1] https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?id=762d2dcd9e233e3025f8627ea65f23e568045edb
[2] https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?id=67a00c299c5c143817c948fbc7de1a2fa1af38fb
[3] https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?id=4c3ddc06cedb62f2904e58fd95170bf206bee149

Signed-off-by: Dario Binacchi <dario.binacchi@amarulasolutions.com>
Signed-off-by: Arnout Vandecappelle <arnout@mind.be>