package/python-yamllint: fix dependencies and SETUP_TYPE
For host build the runtime dependencies have to be added. Also the setup
type needs to be set to 'setuptools'.

./output/host/bin/python ./support/testing/tests/package/sample_python_yamllint.py
Traceback (most recent call last):
  File "/home/hthiery/sources/mainline/buildroot/support/testing/tests/package/sample_python_yamllint.py", line 3, in <module>
    from yamllint import (config, linter)
  File "/home/hthiery/sources/mainline/buildroot/output/host/lib/python3.11/site-packages/yamllint/config.py", line 19, in <module>
    import pathspec
ModuleNotFoundError: No module named 'pathspec'

Signed-off-by: Heiko Thiery <heiko.thiery@gmail.com>
Reported-by: Romain Naour <romain.naour@smile.fr>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>