configs/qemu_ppc64*defconfig: add missing libelf dependency
While building the kernel tools, libelf header is missing:

[...]tools/objtool/include/objtool/elf.h:10:10: fatal error: gelf.h: No such file or directory
   10 | #include <gelf.h>

Select BR2_LINUX_KERNEL_NEEDS_HOST_LIBELF to build host-libelf.

Fixes:
https://gitlab.com/buildroot.org/buildroot/-/jobs/6664587290 (qemu_ppc64le_powernv8_defconfig)
https://gitlab.com/buildroot.org/buildroot/-/jobs/6655119951 (qemu_ppc64le_pseries_defconfig)
https://gitlab.com/buildroot.org/buildroot/-/jobs/6655119946 (qemu_ppc64_pseries_defconfig)

Signed-off-by: Romain Naour <romain.naour@smile.fr>