package/rlwrap: needs MMU
Fix the following build failure raised since the addition of the package
in commit 0a1f2fce0494388080af0a4130e62522c26fe4a9:

/home/autobuild/autobuild/instance-0/output-1/host/riscv64-buildroot-linux-uclibc/bin/ld.real: pty.o: in function `my_pty_fork':
pty.c:(.text+0x68): undefined reference to `fork'
/home/autobuild/autobuild/instance-0/output-1/host/riscv64-buildroot-linux-uclibc/bin/ld.real: filter.o: in function `.L0 ':
filter.c:(.text+0x134): undefined reference to `fork'

Fixes:
 - http://autobuild.buildroot.org/results/0a3a68cfb181bc67a7dbf1d44f64b0a29df75987

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>