package/igt-gpu-tools: disable chamelium
Disable chamelium to avoid the following build failure if gsl is found
but not alsa-lib raised since the addition of the package in commit
d8a729d1731339da141612be33c5e59bc9928748:

In file included from ../lib/igt_audio.c:35:
../lib/igt_audio.h:35:10: fatal error: alsa/asoundlib.h: No such file or directory
   35 | #include <alsa/asoundlib.h>
      |          ^~~~~~~~~~~~~~~~~~

Fixes: d8a729d1731339da141612be33c5e59bc9928748
 - http://autobuild.buildroot.org/results/a7818af881d9aafa9a36f87dc7c882a6880554e8

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>