package/botan: fix uclibc build
getentropy is enabled by default since version 3.0 and
https://github.com/randombit/botan/commit/8642f2a99deefc85cdb512ee50d9f62c5e0ae4b8
and explicit_bzero is also enabled since version 3.0 and
https://github.com/randombit/botan/commit/e6819a380fb67c1be546dc618248b62d93266423
resulting in the following build failure since bump to version 3.2.0 in
commit 2f8feb66204ff661e9fd5f508e2dfd1ebc0f2813:

src/lib/entropy/getentropy/getentropy.cpp:26:9: error: '::getentropy' has not been declared; did you mean 'Getentropy'?
   26 |    if(::getentropy(buf.data(), buf.size()) == 0) {
      |         ^~~~~~~~~~
      |         Getentropy

Fixes: 2f8feb66204ff661e9fd5f508e2dfd1ebc0f2813
 - http://autobuild.buildroot.org/results/d58c4730c770467b42af426545dd917ecc5fed17

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle <arnout@mind.be>