package/linux-tools: fix selftests with kernel >= 6.5
Fix the following selftests build failure raised since kernel >= 6.5 and
https://github.com/torvalds/linux/commit/9fc96c7c19dfab67bf81b25fbc4f49b7752d5060:

make[1]: Entering directory '/home/autobuild/autobuild/instance-4/output-1/build/linux-6.6.3/tools/testing/selftests'

error: missing kernel header files.
Please run this and try again:

    cd ../../..
    make headers

make[1]: *** [Makefile:186: kernel_header_files] Error 1

Fixes:
 - http://autobuild.buildroot.org/results/7674abb454b46ca768e44b6838a0d8724c772dd6

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>